version: "3.12"
services:
  test:
    image: "exercise-1"
    volumes:
      - .:/app:Z
    command: python3 -m pytest
  run:
    image: "exercise-1"
    volumes:
      - .:/app:Z
    command: python3 main.py